### ISSUE TITLE
Mediakeys plugin installation broken

### ISSUE THREAD

**Issue by osus** [blackberry/WebWorks-Community-APIs#422]
cordova-plugin-mediakeys can't be installed, it returns error.
It seems that the binary files have been removed from the repository and the installer can't found.
Just try to install the plugin to see the error.

C:\project>cordova plugin add cordova-plugin-mediakeys

Fetching plugin "cordova-plugin-mediakeys" via npm
Installing "cordova-plugin-mediakeys" for blackberry10
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-mediakeys':Error: Uh oh!
"C:\project\plugins\cordova-plugin-mediakeys\src\blackberry10\native\device\libMediaKeys.so" not found!
    at Object.module.exports.common.copyFile (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\common.js:38:40)
    at Object.module.exports.lib-file.install (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\blackberry10.js:71:20)
    at installWrapper (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:77:32)    at Object.ActionStack.process (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:68:25)
    at handleInstall (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:576:20)
    at C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:363:28
    at _fulfilled (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
Error: Uh oh!
"C:\project\plugins\cordova-plugin-mediakeys\src\blackberry10\native\device\libMediaKeys.so" not found!
    at Object.module.exports.common.copyFile (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\common.js:38:40)
    at Object.module.exports.lib-file.install (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\blackberry10.js:71:20)
    at installWrapper (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:77:32)
    at Object.ActionStack.process (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:68:25)
    at handleInstall (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:576:20)
    at C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:363:28
    at _fulfilled (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\jesus.iglesias\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49

**Comment by timwindsor** [comment]
Sorry - I messed this up when I published. It's fixed now with version 1.0.1
